# Generated by Django 5.0.6 on 2024-06-24 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_room', models.CharField(max_length=10)),
                ('status_booking', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DateBookingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('room_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.rooms')),
            ],
        ),
        migrations.CreateModel(
            name='TimesBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start_booking', models.TimeField()),
                ('time_finish_booking', models.TimeField()),
                ('date_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.datebookingroom')),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
